package pl.codepot.groovy_no_way_back.factory;

import pl.codepot.groovy_no_way_back.dto.GitHubRepo;

public final class GitHubRepoFactory {
    public static GitHubRepo newAndroidMaze() {
        GitHubRepo androidMaze = new GitHubRepo();
        androidMaze.id = 24003843L;
        androidMaze.name = "AndroidMaze";
        androidMaze.full_name = "OrdonTeam/AndroidMaze";
        androidMaze.owner = GitHubUserFactory.newOrdonTeam();
        androidMaze.isPrivate = false;
        androidMaze.htmlUrl = "https://github.com/OrdonTeam/AndroidMaze";
        androidMaze.description = "";
        androidMaze.fork = false;
        androidMaze.url = "https://api.github.com/repos/OrdonTeam/AndroidMaze";
        androidMaze.forksUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/forks";
        androidMaze.keysUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/keys{/key_id}";
        androidMaze.collaboratorsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/collaborators{/collaborator}";
        androidMaze.teamsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/teams";
        androidMaze.hooksUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/hooks";
        androidMaze.issue_eventsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/issues/events{/number}";
        androidMaze.eventsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/events";
        androidMaze.assigneesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/assignees{/user}";
        androidMaze.branchesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/branches{/branch}";
        androidMaze.tagsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/tags";
        androidMaze.blobsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/git/blobs{/sha}";
        androidMaze.gitTagsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/git/tags{/sha}";
        androidMaze.gitRefsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/git/refs{/sha}";
        androidMaze.treesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/git/trees{/sha}";
        androidMaze.statusesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/statuses/{sha}";
        androidMaze.languagesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/languages";
        androidMaze.stargazersUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/stargazers";
        androidMaze.contributorsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/contributors";
        androidMaze.subscribersUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/subscribers";
        androidMaze.subscriptionUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/subscription";
        androidMaze.commitsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/commits{/sha}";
        androidMaze.gitCommitsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/git/commits{/sha}";
        androidMaze.commentsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/comments{/number}";
        androidMaze.issueCommentUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/issues/comments{/number}";
        androidMaze.contentsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/contents/{+path}";
        androidMaze.compareUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/compare/{base}...{head}";
        androidMaze.mergesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/merges";
        androidMaze.archiveUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/{archive_format}{/ref}";
        androidMaze.downloadsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/downloads";
        androidMaze.issuesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/issues{/number}";
        androidMaze.pullsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/pulls{/number}";
        androidMaze.milestonesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/milestones{/number}";
        androidMaze.notificationsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/notifications{?since,all,participating}";
        androidMaze.labelsUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/labels{/name}";
        androidMaze.releasesUrl = "https://api.github.com/repos/OrdonTeam/AndroidMaze/releases{/id}";
        androidMaze.created_at = "2014-09-13T19:37:37Z";
        androidMaze.updated_at = "2015-03-01T13:43:22Z";
        androidMaze.pushed_at = "2014-10-27T10:38:41Z";
        androidMaze.gitUrl = "git://github.com/OrdonTeam/AndroidMaze.git";
        androidMaze.sshUrl = "git@github.com:OrdonTeam/AndroidMaze.git";
        androidMaze.cloneUrl = "https://github.com/OrdonTeam/AndroidMaze.git";
        androidMaze.svnUrl = "https://github.com/OrdonTeam/AndroidMaze";
        androidMaze.homepage = null;
        androidMaze.size = 732;
        androidMaze.stargazersCount = 2;
        androidMaze.watchersCount = 2;
        androidMaze.language = "Groovy";
        androidMaze.has_issues = true;
        androidMaze.has_downloads = true;
        androidMaze.has_wiki = true;
        androidMaze.has_pages = false;
        androidMaze.forksCount = 0;
        androidMaze.mirrorUrl = null;
        androidMaze.openIssuesCount = 0;
        androidMaze.forks = 0;
        androidMaze.openIssues = 0;
        androidMaze.watchers = 2;
        androidMaze.default_branch = "master";
        androidMaze.networkCount = 0;
        androidMaze.subscribersCount = 5;
        return androidMaze;
    }
}
